name: expenses_repository
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  flutterfire_cli: ^1.0.0
  firebase_core: ^3.2.0

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
